# Generated by Django 4.2.1 on 2023-06-05 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="author",
        ),
    ]
